// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hometask.Data;

#nullable disable

namespace hometask.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260317233635_addedRotationStartDate")]
    partial class addedRotationStartDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hometask.Entities.HouseArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HouseAreas");
                });

            modelBuilder.Entity("hometask.Entities.HouseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseAreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RotationIndex")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RotationStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HouseAreaId");

                    b.ToTable("HouseTasks");
                });

            modelBuilder.Entity("hometask.Entities.HouseTaskCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedById")
                        .HasColumnType("text");

                    b.Property<Guid>("HouseTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompletedById");

                    b.HasIndex("PersonId");

                    b.HasIndex("HouseTaskId", "WeekStart")
                        .IsUnique();

                    b.ToTable("HouseTasksCompletions");
                });

            modelBuilder.Entity("hometask.Entities.HouseTaskParticipant", b =>
                {
                    b.Property<Guid>("HouseTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonId")
                        .HasColumnType("text");

                    b.Property<int>("RotationOrder")
                        .HasColumnType("integer");

                    b.HasKey("HouseTaskId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("HouseTasksParticipants");
                });

            modelBuilder.Entity("hometask.Entities.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("hometask.Entities.HouseTask", b =>
                {
                    b.HasOne("hometask.Entities.HouseArea", "HouseArea")
                        .WithMany()
                        .HasForeignKey("HouseAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseArea");
                });

            modelBuilder.Entity("hometask.Entities.HouseTaskCompletion", b =>
                {
                    b.HasOne("hometask.Entities.Person", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById");

                    b.HasOne("hometask.Entities.HouseTask", "HouseTask")
                        .WithMany("Completions")
                        .HasForeignKey("HouseTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hometask.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedBy");

                    b.Navigation("HouseTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("hometask.Entities.HouseTaskParticipant", b =>
                {
                    b.HasOne("hometask.Entities.HouseTask", "HouseTask")
                        .WithMany("Participants")
                        .HasForeignKey("HouseTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hometask.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseTask");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("hometask.Entities.HouseTask", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
